apiVersion: v1
kind: Secret
metadata:
  name: ranchat-secrets
type: Opaque
data:
  API_KEY: [INSERT_HERE_BASE64_ENCODED_API_KEY]
  S3_KEY: [INSERT_HERE_BASE64_ENCODED_S3_KEY]
  S3_SECRET_ACCESS_KEY: [INSERT_HERE_BASE64_ENCODED_S3_SECRET_ACCESS_KEY]
